### ISSUE TITLE
VirtualMachine.removeStorageController() unittest failing

### ISSUE THREAD

**Issue by von** [von/pyVBox#2]
The unittest for VirtualMachine.removeStorageController() is failing (see below) for reasons not clear to me. I've neutered the test (VirtualMachineTests.testAddStorageControllers()) for now (first line is 'return').

<pre><code>
======================================================================
ERROR: Test adding and removing of StorageController to a VirtualMachine
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vwelch/develop/pyVBox/test/VirtualMachineTests.py", line 130, in testAddStorageControllers
    machine.removeStorageController(controller2.name)
  File "/Users/vwelch/develop/pyVBox/pyVBox/VirtualMachine.py", line 416, in removeStorageController
    VirtualBoxException.handle_exception(e)
  File "/Users/vwelch/develop/pyVBox/pyVBox/VirtualMachine.py", line 414, in removeStorageController
    self.getIMachine().removeStorageController(name)
  File "<XPCOMObject method 'removeStorageController'>", line 3, in removeStorageController
VirtualBoxOperationAborted: Operation aborted (NS_ERROR_ABORT)
</code></pre>

**Comment by von** [comment]
Subsequent to getting the above error, I get errors for other operations (that should work) in the same process, e.g.:

<pre><code>
======================================================================
ERROR: Test VirtualMachine.clone() method
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/von/develop/pyVBox/test/VirtualMachineTests.py", line 165, in testClone
    machine = VirtualMachine.open(self.testVMpath)
  File "/Users/von/develop/pyVBox/pyVBox/VirtualMachine.py", line 154, in open
    VirtualBoxException.handle_exception(e)
  File "/Users/von/develop/pyVBox/pyVBox/VirtualMachine.py", line 152, in open
    machine = cls._vbox.openMachine(path)
  File "<XPCOMObject method 'openMachine'>", line 3, in openMachine
VirtualBoxFileNotFoundException: Operation failed (NS_ERROR_FAILURE)
</code></pre>

**Comment by von** [comment]
This seemed to just work after upgrading to 4.1.2 and fixing the code to use the new API.
